[package]
name = "bevy_nannou_derive"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full"] }
quote.workspace = true

[dev-dependencies]
bevy.workspace = true
bevy_nannou_draw = { path = "../bevy_nannou_draw" }