[package]
name = "bevy_nannou_draw"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
lyon = "0.17"
nannou_core = { path = "../nannou_core" }
rusttype = { version = "0.8", features = ["gpu_cache"] }
num-traits = "0.2"
bytemuck = "1.15.0"
rayon = "1.10"
uuid = "1.8"