[package]
name = "tui_example_browser"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
toml = "0.8.20"

[[bin]]
name = "tui_example_browser"
path = "main.rs"
