name: nannou
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

# If a new commit is pushed to a PR, cancel any in-progress work on the same PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cargo:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: fmt
            command: cargo fmt --verbose --all -- --check
          - name: check
            command: cargo check --locked --workspace
          - name: check-examples
            command: cargo check --locked --examples --workspace
          - name: check-all-features
            command: cargo check --locked --examples --workspace --all-features
          - name: test-core
            command: cargo test --locked -p nannou_core --no-default-features --features "libm serde"
          - name: test-book
            command: cargo test --locked -p book_tests
          - name: book
            command: mdbook build guide/
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Install Linux dependencies
      run: >
        sudo apt-get update &&
        sudo apt-get install --no-install-recommends -y
        libasound2-dev
        libudev-dev
        libwayland-dev
        libxkbcommon-dev
        libvulkan-dev
        libclang-dev
        libavcodec-dev
        libavformat-dev
        libavutil-dev
        libavfilter-dev
        libavdevice-dev
        libswscale-dev
        libswresample-dev
        pkg-config
    - name: Install mdbook
      if: matrix.name == 'book'
      run: cargo install mdbook --locked
    - name: ${{ matrix.name }}
      run: ${{ matrix.command }}

  verifications:
    needs: [cargo]
    runs-on: ubuntu-latest
    steps:
    - run: echo "Verifications complete"

  # Publish all the crates.
  cargo-publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [verifications]
    env:
      CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Cargo publish nannou_core
      continue-on-error: true
      run: cargo publish --token $CRATESIO_TOKEN --manifest-path nannou_core/Cargo.toml
    - name: Cargo publish nannou_wgpu
      continue-on-error: true
      run: cargo publish --token $CRATESIO_TOKEN --manifest-path nannou_wgpu/Cargo.toml
    - name: Cargo publish nannou_mesh
      continue-on-error: true
      run: cargo publish --token $CRATESIO_TOKEN --manifest-path nannou_mesh/Cargo.toml
    - name: Cargo publish nannou
      continue-on-error: true
      run: cargo publish --token $CRATESIO_TOKEN --manifest-path nannou/Cargo.toml
    - name: Cargo publish nannou_audio
      continue-on-error: true
      run: cargo publish --token $CRATESIO_TOKEN --manifest-path nannou_audio/Cargo.toml
    - name: Cargo publish nannou_laser
      continue-on-error: true
      run: cargo publish --token $CRATESIO_TOKEN --manifest-path nannou_laser/Cargo.toml
    - name: Cargo publish nannou_osc
      continue-on-error: true
      run: cargo publish --token $CRATESIO_TOKEN --manifest-path nannou_osc/Cargo.toml
    - name: Cargo publish nannou_egui
      continue-on-error: true
      run: cargo publish --token $CRATESIO_TOKEN --manifest-path nannou_egui/Cargo.toml

  # Publish the guide by pushing it to `deploy` branch.
  guide-push-to-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [verifications]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Install mdbook
      run: cargo install mdbook --locked
    - run: mdbook build guide/
    - name: Commit book to deploy branch
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git remote add nannou-org https://${{ secrets.DEPLOY_GUIDE_TOKEN }}@github.com/${{ github.repository }}.git
        git fetch nannou-org &&
        git config credential.helper "store --file=.git/credentials" &&
        echo "https://${{ secrets.DEPLOY_GUIDE_TOKEN }}:@github.com" > .git/credentials &&
        git checkout deploy &&
        cp -r guide/book/* . &&
        git add -A . &&
        git commit -m "Automated commit in preparation for deployment: $GITHUB_RUN_NUMBER" || true
    - name: Push changes to deploy branch
      run: |
        git push --force --quiet nannou-org deploy &>/dev/null
